//
//  TableViewController.swift
//  LookBook
//
//  Created by Janice Flint on 4/11/22.
//

import UIKit

class TableViewController: UITableViewController {
    
    var deck = [NSDictionary]()
    var include = [String]()
    var dateModified = Date()

    override func viewDidLoad() {
        super.viewDidLoad()
        initializeDeck()

        // Uncomment the following line to preserve selection between presentations
        // self.clearsSelectionOnViewWillAppear = false

        // Uncomment the following line to display an Edit button in the navigation bar for this view controller.
        // self.navigationItem.rightBarButtonItem = self.editButtonItem
    }

    // MARK: - Table view data source

    override func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        // #warning Incomplete implementation, return the number of rows
        return deck.count
    }
 
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let cell = tableView.cellForRow(at: indexPath)
/*        let personInfo  = deck[indexPath.row]
        var p = personInfo.mutableCopy()
        if personInfo["include"] as! String == "Yes"  {
            cell?.accessoryType = .none
            personInfo["include"] = "No"
        } else {
            cell?.accessoryType = .checkmark
            personInfo["include"]  = "Yes"
        }
        deck[indexPath.row] = personInfo as NSDictionary
        UserDefaults.standard.set(deck, forKey: "deck")
 */
        if include[indexPath.row] == "Yes" {
            cell?.accessoryType = .none
            include[indexPath.row] = "No"
        } else {
            cell?.accessoryType = .checkmark
            include[indexPath.row] = "Yes"
        }
        UserDefaults.standard.set(include, forKey: "include")
    }

    func initializeDeck() {
        if UserDefaults.standard.object(forKey: "deck") != nil {
            deck = UserDefaults.standard.array(forKey: "deck") as! Array
                include = UserDefaults.standard.array(forKey: "include") as! [String]
            dateModified = UserDefaults.standard.object(forKey: "dateModified") as! Date
            //print("Deck",deck)
        }
        else {
            deck = [[
            "formalName" : "Viaduct",
            "nickName" : "Viaduct",
            "title" : "Company",
            "bio" : "Viaduct delivers proven value to the rapidly-changing automotive industry with AI-powered applications that help OEMs, suppliers, and fleets improve product quality, streamline manufacturing, lower warranty expense, improve customer experience, and generate new revenue streams. \n\n Viaduct’s machine learning solutions allow OEMs to manage, analyze, and utilize the data generated by their connected vehicles.\n\nViaduct is a cloud platform derives actionable insights from connected vehicle data to power applications,   such as predictive maintenance, driver identification, and driver safety scores. Deployed in the vehicle, Viaduct’s machine learning solutions intelligently compress and enhance vehicle data to allow the richest data to be transmitted to the cloud in the fewest bytes.",
            "image" : "viaduct.png",
            "include" : "Yes",
            "notes" : "Funding Round - Jun 10, 2020. Viaduct raised $11,000,000 / Series A from BoxGroup and 2 other investors"
            ], [
                 "formalName" : "ADHITA SELVARAJ",
            "nickName" : "Adhita",
            "title" : "Software Engineer",
            "bio" : "Adhita Selvaraj (he/him) is a Software Engineer in ML Infrastructure. His expertise is in building developer tooling and platforms for Data Scientists. Prior to Viaduct, he worked at Cisco where he was building Kubeflow in OSS and into Cisco products. He has a Master's degree from Stony Brook where he started contributing to Cloud Native OSS projects.",
            "image" : "adhita.png",
            "include" : "Yes",
            "notes" : "He didn't come to retreat. ADHD 3 weeks off because he couldn't work. Done a lot of work on open source projects, not that productive, John not a good manager for him, socially ackward"
            ], [
                "formalName" : "ALJAŽ KOŠMERLJ",
                "nickName" : "Aljaz",
                "title" : "Data Scientist",
                "bio" : "Aljaž is a Data Scientist at Viaduct. He holds a PhD in Artificial Intelligence from the University of Ljubljana. Before joining Viaduct he worked as a Researcher at the Jožef Stefan Institute in Ljubljana on applied AI projects with a focus on Stream Learning and Natural Language Processing. Besides research projects, he developed solutions for Bloomberg LP and the Slovenian Ministry of Justice. ",
                "image" : "aljaz.png",
                "include" : "Yes",
                "notes" : "All-ye-ash Slovenia, working on the battery model, into medeval martial arts, fight with swords all-eash, hired same time as Ken, really into Lord of the Rings, he does Tango, ballroom dancing competitions, his wife is his high school sweetheart, He's very nice, social, Viaduct has two customers: Packard- own Kenmore, Peterbuilt and Doff truck companies, Clarios -  is new custiomer, supply batteries to customers, they don't have any data, use to make Sears did-hard batteries for cars and trucks"
            ], [
                "formalName" : "AMIRMEHDI SHARIFZAD",
                "nickName" : "Amir",
                "title" : "Data Scientist",
                "bio" : "Amirmehdi has recently graduated from the University of Waterloo with a major in Computer Science and a focus on Machine Learning and Deep Learning. He has worked on various Data Science projects as an intern throughout his undergraduate. Prior to joining Viaduct he worked on state-of-the-art Neural Machine Translation and Natural Language Processing research at Huawei's Noah's Ark Lab.",
                "image" : "amirmehdi.png",
                "include" : "Yes",
                "notes" : "Iranian, has 2 brothers, Amir, he's the middle child, lives in Redwood City, plays ping pong, came to our house, nice, adrenaline junkie, did work on claim trends for 3 months, couldn't be put in product, comes in office 2 days a week, for social, plays piano - played at retreat"
            ], [
/*                "Viaduct" : "Iashe runs team the analytic team that uses the Product at PACCAR, asian is scary, makes people feel bad, but think David is smart, loves David, PACCAR analytics is not as good as Viaduct and trusts smart David, Guy is now in charge of PACCAR relationship, now Iesha trusts him thinks good enough, PACCAR wants to invest in, CIO wanted to meet with David, Viaduct does not want to take money because it would change who would want to do business with Viaduct"
 3 people started Monday -
 Jack - another Guy, customer relationship for Clarios, lives in Chicago, plays piano, played at retreat, does jujuitsu
 Luka - retreat with girlfriend, use to work with Niko, lives in Slovenia, Luka was the lead when working with Niko, plays guitar and piano, wouldn't play piano at retreat, tatoos, drank lots of beer
 Robert - Slovenian, new, retreat, leaving second week, introvert nerd, data scientist that can also program,
 Valero - use to work at Kanjoya, from Mondolva, lives in Sunnyvale, met his wife in Mondolva, they just moved here she use to do interior designing, but working at Stanford doing QA, he's part time, he has another job, use to live bay area, then moved to Mondolva to find wife, learned salsa dancing to meet someone, Kanjoya let him work remotely, mainly directed by Neil
 */
                "formalName" : "BORA UYUMAZTURK",
                "nickName" : "Bora",
                "title" : "Product Manager",
                "bio" : "Bora is a Product Manager at Viaduct. He specializes in statistical and mathematical modeling. Previously, he was a research assistant in the Stanford Machine Learning Group, where he published research at the intersection of artificial intelligence and medicine. In addition to research, he’s also taught machine learning concepts as a course assistant at deeplearning.ai. He holds an MS in computer science and a BS in mathematics, both from Stanford University.",
                "image" : "bora.png",
                "include" : "Yes",
                "notes" : "lives in Washington DC, didn't come to retreat, more of a an introvert, stutters, super smart, he knows data science really well, he's in product, likes to be in charge, controlling, liked the thing everyone does one thing at a time, very organized, he's been with Viaduct for a long time, he disapears sometimes"
            ], [
                "formalName" : "DAVID HALLAC",
                "nickName" : "David",
                "title" : "Founder & CEO",
                "bio" :"David is the Founder and CEO of Viaduct. His background is in large-scale optimization for time series sensor data. David received his PhD in Electrical Engineering from Stanford University, where he focused on developing mathematical models for finding patterns in temporal data, and his open-source software has been directly used by companies including Volkswagen, Boeing, and Bosch. Prior to Stanford, David received his B.S. in Electrical Engineering from the University of Pennsylvania.",
                "image" : "David.png",
                "include" : "Yes",
                "notes" : "Married to Bonnie, baby due late June, live in Palo Alto, played on Stanford Badmitton team, he was the captain of the team"
            ], [
                "formalName" : "GUI ANNUNCIACAO",
                "nickName" : "Gui",
                "title" : "Senior Product Manager",
                "bio" : "Guilherme (Gui) is Senior Product Manager at Viaduct. Before this role, he was part of the owner experience team at Tesla, where he conceptualized, designed, and implemented digital experiences to delight owners and help scale customer support and service operations. Gui holds an MBA from UC Berkeley Haas School of Business, and is passionate about solving large-scale integrated issues in the transportation and mobility industry.",
                "image" : "gui.png",
                "include" : "Yes",
                "notes" : "Gee, lives in Sunnyvale, father was a minister, grew in Brazil until 13, speaks Portuguez, He use to work at Tesla, does a lot of customer research, Matt doesn't trust him, he researches things, Matt trusts Bora much more, gives Gui less to do, Gui was assigned what to do on retreat, social but not trusted on what to do in product"
            ], [
                "formalName" : "GUY STEVENS",
                "nickName" : "Guy",
                "title" : "Data Science Lead",
                "bio" : "Guy is the Data Science Lead at Viaduct. He holds an MBA from the University of Chicago and a BA in Mathematics and Economics from Pomona College. Prior to joining Viaduct, he spent eight years in the front office of a Major League Baseball team, where he led research and development efforts in support of baseball operations. He enjoys tackling complex data science challenges to develop impactful and accessible decision-making tools. ",
                "image" : "guy.png",
                "include" : "Yes",
                "notes" : "money ball guy for Kansis city Royals baseball team, went to Pomono, pitcher, pitched Isreal national baseball team, super smart, really nice, he didn't come to retreat because he had surgery to implant something and recovering, coming following week, he can stand up to PACCAR Iesha, which leaves David able to have time to raise money, be CEO"
            ], [
                "formalName" : "HARITHA CHITALIA",
                "nickName" : "Haritha",
                "title" : "Product Manager",
                "bio" : "Haritha is a Product Manager at Viaduct. Before this role, she worked on designing and implementing products for life-sciences companies conducting large-scale clinical trails at Saama Technologies. She is passionate about surfacing actionable data insights from complex data sets, drive efficiency in decision making, and delight customers with intuative product designs. Haritha graduated with a Bachelors of Science degree in Computer Science from Georgia Institute of Technology and is excited to take on the Connected Vehicle space.",
                "image" : "haritha.png",
                "include" : "Yes",
                "notes" : "lives in Santa Clara, pregnant, due same time as Bonnie, she's nice, but let's people rollover, may not be at retreat, likes Ken because he validates she's right and validate her to stand her ground, Matt intimidates her"
            ], [
                "formalName" : "JERNEJ LIPOVEC",
                "nickName" : "Jernej",
                "title" : "Software Engineer",
                "bio" : "Jernej is a Software Engineer at Viaduct. He is a Frontend specialist and experienced with JavaScript, React, and Flutter and is always looking to automate everything he can to improve his team’s developer experience. Jernej holds a Bachelor's degree in Computer and Information Science from the University of Ljubljana, where he graduated with a thesis about price prediction of highly fluctuating products on online trading platforms.",
                "image" : "jernejl.png",
                "include" : "Yes",
                "notes" : "yer-nay, new, Slovenia, gamer, not as social, plays badmitton and rides motorcycles, use to be a swimmer, 15 month old girl, he's full stack, works from home, he's at retreat, only staying first week because of baby, doesn't go in the office, Ken just gave him a big raise because he's really good."
            ], [
                "formalName" : "HIMA BINDU BHARDWAJ",
                "nickName" : "Hima",
                "title" : "Data Scientist",
                "bio" : "Hima holds a Masters in Data Science from Columbia University, New York. She has previously worked on Data Science problems focused on fortifying cities against natural disasters, analyzing the history of New York City, and solving a business problem related to return propensity at Ralph Lauren. She is a scholar and fellow at various technical and social organizations like TEDx, Google, WeTech-Qualcomm, IEEE, AnitaB.org, and The Data Science Institute at Columbia University.",
                "image" : "Hima.png",
                "include" : "Yes",
                "notes" : "lives in Redwood City, brought exploding Kittens, Amir and her live in Redwood City, just moved in new apartment, comes into the office for social context,two days, shy but social"
            ], [
                "formalName" : "JERNEJ OBLAK",
                "nickName" : "Jernej",
                "title" : "Software Engineer",
                "bio" : "Jernej is a software engineer with focus on front-end facing features, but enjoys optimising any code or process. He's been working on improving various development workflows and finding solutions to specific system designs problems. He developed various webpages and applications, worked on unique web-apps and intranets and was often involved with UI/UX professionals while developing front-facing features. He holds a Bachelor's degree in Computer and Information Science from the University of Ljubljana. He also enjoys mentoring and discussing strategies and improvements whilst focusing on compassion and understanding. .",
                "image" : "jernejo.png",
                "include" : "Yes",
                "notes" : "Jerry goes buy, Slovenia, he goes in office, skateboarder, backpacker, mountain biker, vegan, came to the retreat,he's been with Viaduct for a year, his girlfriend is coming for second part of retreat, Ken talked about going backpacking"
            ], [
                "formalName" : "JIM BRADY",
                "nickName" : "Jim",
                "title" : "Head of BD",
                "bio" : "Jim is Head of Business Development at Viaduct. He has spent his entire career within the automotive industry, holding key leadership positions at General Motors, as well as being an industry consultant guiding companies to develop and implement mobility experiences. While at GM, he led global customer experience, and corporate strategy for connected vehicle ecosystem, with the goal to transform GM into a customer-centric and innovative organization. Jim is passionate about delivering innovative solutions that change and disrupt the automotive mobility industry.",
                "image" : "jim.png",
                "include" : "Yes",
                "notes" : "came to retreat, lives in Detroit?, worked in auto business for 20 years, has connections, get Viaduct into accounts,has kids, more superficial, not as deep, family man, nice "
            ], [
                "formalName" : "JOE PHILLIPS",
                "nickName" : "Joe",
                "title" : "Director of Sales",
                "bio" : "Joe is the Director of Sales at Viaduct. He attended the University of Oregon (Go Ducks!) and received his bachelor's in East Asian literature and Business. He's spent the bulk of his career working with cutting-edge machine learning teams to scale their efforts and bring models to market. Some of his clients included companies like Tesla, Boeing, Shell, Microsoft, Google, and Facebook.",
                "image" : "joe.png",
                "include" : "Yes",
                "notes" : "came to our house, 1 year old, daughter screams when she's happy, lives in the east bay, Orinda?, comes into the office Mon and Wed"
            ], [
                "formalName" : "JOHN PUGLIESI",
                "nickName" : "Bora",
                "title" : "Software Engineer Lead",
                "bio" : "John is a Software Engineer Lead at Viaduct. His expertise is in big data systems infrastructure. Prior to Viaduct, John developed performance, auto-scaling, and incident management systems for a global customer experience management platform at Medallia. He holds a dual-degree in Computer Science and Business Administration from the University of Southern California.",
                "image" : "John.png",
                "include" : "Yes",
                "notes" : "Devon's roommate, live in the east bay"
        ], [
                "formalName" : "KEN ANDERSON",
                "nickName" : "Ken",
                "title" : "Head of Engineering",
                "bio" : "Ken is Head of Engineering at Viaduct. He loves building and managing teams and providing software solutions that deliver customer value. Ken worked at Adobe for 21 years, 15 of which were spent managing the teams that built PDF, Adobe Acrobat, Adobe Reader, and Adobe’s first document cloud product. After Adobe, Ken started a mobile software company that he ran for 7 years, then did two successful startups in the Machine Learning space, focused on Natural Language Processing and predictive analytics for employee and customer data.",
                "image" : "ken.png",
                "include" : "Yes",
                "notes" : " "
            ], [
                "formalName" : "MINAL MEHTA",
                "nickName" : "Minal",
                "title" : "Talent Acquisitions",
                "bio" : "Minal leads Talent Acquisitions at Viaduct. She has extensive experience recruiting for startups and supporting them through their growth. Before Viaduct, she worked in recruiting at TripActions, Cruise, and Ooma. Creating a culture of transparency and success is her biggest passion, and she is focused on bringing together a diverse team that launches Viaduct to its next stage of growth",
                "image" : "minal.png",
                "include" : "Yes",
                "notes" : "lives in Sunnyvale, has kids 12 ish, Ken works with her alot, planned the retreat help from Gui, she's going to New York"
            ], [
                "formalName" : "NIKO COLNERIČ",
                "nickName" : "Niko",
                "title" : "Software Engineer",
                "bio" : "Niko is a Software Engineer at Viaduct. Prior to joining Viaduct as an independent contractor, he worked on microservice-oriented backend systems at Cytora and Reciprocity, and contributed to open-source software for data mining and visualization toolbox Orange. He holds a PhD in Computer Science from the University of Ljubljana focusing on natural language processing with neural networks.",
                "image" : "Niko.png",
                "include" : "Yes",
                "notes" : "Ken promoted to be tech lead in Slovenia, smart and nice, Nice person, Ken drove with him to retreat, he goes into office, super competent, family? he rents the office, work as independent contractors for thier taxes, they are contractors, goes in office twice a week, walks 10 min to office"
            ], [
                "formalName" : "MATEJ DREV",
                "nickName" : "Matej",
                "title" : "COO",
                "bio" : "Matej is COO at Viaduct. He holds a PhD in Public Policy and Management from Carnegie Mellon University. Prior to joining Viaduct, he was an Engagement Manager with McKinsey & Co. in San Francisco where he helped large companies in a variety of industries solve challenges that lie at the intersection of strategy and corporate finance. Before McKinsey, he served as a tenure-track Assistant Professor of Economics at Georgia Institute of Technology where he led research projects and taught graduate courses focused on innovation economics & management.",
                "image" : "Matej.png",
                "include" : "Yes",
                "notes" : "lives in Benicia, has girlfriend or wife in Benicia, spent last 2 months in Slovenia because his mother had heart attck, he knows David's advisor, he's came to retreat,"
            ], [
                "formalName" : "MATTHEW HOWARD",
                "nickName" : "Matt",
                "title" : "Head of Product",
                "bio" : "Matt is Head of Product at Viaduct. He loves leveraging data to deliver impactful products to market and is excited about game-changing opportunities in the connected car ecosystem. Most recently, Matt was the Head of Product Management for the Lumada Software portfolio at Hitachi Vantara. He has also held leadership roles at Anaplan (IPO), Merced Systems (Nice Systems), and Siebel Systems (Oracle). He started his career as an engineer at Xerox PARC, where he developed electronic paper. Matt earned a BS/MS from Stanford University and an MBA from Harvard Business School. ",
                "image" : "matt.png",
                "include" : "Yes",
                "notes" : "lives in the east Bay? grew up in Marin, has a family, has teenage kids, knows a lot about machine learning, researching automotive, he comes in office maybe once a week, does back country skiing, surfs but says he's not very good"
            ], [
                "formalName" : "WENLI LOOI",
                "nickName" : "Wenli",
                "title" : "ML Engineer",
                "bio" : "Wenli is a Machine Learning Engineer at Viaduct. Prior to Viaduct, he worked on a large-scale internal data processing framework at Google and on sociological data science research with the SNAP Group at Stanford. He holds an MS in computer science from Stanford University and BS in computer science and chemical engineering from University of Calgary.",
                "image" : "Wenli.png",
                "include" : "Yes",
                "notes" : "Wen-Lee, Builds tooling to make machine learining pipelines efficient, Hima Amir Alijz use his pipelines, john does the same work, wenli knows more than John, data scientist that builds tooling, snowflake, delay, talk fast, thinks in between"
           ]]
            dateModified = Date()
            for _ in deck {
                include += ["Yes"]
            }
            UserDefaults.standard.set(include, forKey: "include")
            UserDefaults.standard.set(dateModified, forKey: "dateModified")
            UserDefaults.standard.set(deck, forKey: "deck")
            print(deck)
        }
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
        let personInfo = deck[indexPath.row]
        cell.textLabel?.text = personInfo["formalName"] as! String?
/*        if personInfo["include"] as! String == "Yes" {
            cell.accessoryType = .checkmark
        }
        else {
            cell.accessoryType = .none
        } */
        if include[indexPath.row] == "Yes" {
            cell.accessoryType = .checkmark
        }
        else {
            cell.accessoryType = .none
        }
       return cell
    }

    /*
    // Override to support conditional editing of the table view.
    override func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        // Return false if you do not want the specified item to be editable.
        return true
    }
    */

    /*
    // Override to support editing the table view.
    override func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) {
        if editingStyle == .delete {
            // Delete the row from the data source
            tableView.deleteRows(at: [indexPath], with: .fade)
        } else if editingStyle == .insert {
            // Create a new instance of the appropriate class, insert it into the array, and add a new row to the table view
        }    
    }
    */

    /*
    // Override to support rearranging the table view.
    override func tableView(_ tableView: UITableView, moveRowAt fromIndexPath: IndexPath, to: IndexPath) {

    }
    */

    /*
    // Override to support conditional rearranging of the table view.
    override func tableView(_ tableView: UITableView, canMoveRowAt indexPath: IndexPath) -> Bool {
        // Return false if you do not want the item to be re-orderable.
        return true
    }
    */

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destination.
        // Pass the selected object to the new view controller.
    }
    */

}
